### ISSUE TITLE
想问下大概什么时候支持评论呢

### ISSUE THREAD

**Issue by zhu-xiaowei** [funnyzak/react-native-quick-start#275]
### Description

想问下大概什么时候支持发表评论呢

### Why

希望尽快添加评论功能。

### Alternatives

.

**Comment by funnyzak** [comment]
@zhu-xiaowei 
目前V2EX官方只系统了查询相关的开放API。
做互动功能的话，目前只能通过模拟请求官网解析数据做到。
后面有时间具体看下。
