### ISSUE TITLE
这个可以结合ant-design-mobile-rn一起用吗

### ISSUE THREAD

**Issue by grojef** [funnyzak/react-native-quick-start#287]
### Description

我发现自带的组件缺少一些表单组件，如果能引入ant-design-mobile-rn 应该会节省很多工作

### Why

缺少selector,radio等表单组件

### Alternatives

缺少selector,radio等表单组件

**Comment by funnyzak** [comment]
目前没有引入外部UI组件库。引入ant-design，可能需要做一些全局样式适配微调。
