### ISSUE TITLE
拉取最新代码（0.71.5）无法运行

### ISSUE THREAD

**Issue by googxho** [funnyzak/react-native-quick-start#306]
### Description

报错如下图：win10 + Android 环境下能正常跑入门程序

![tmpB0D3](https://user-images.githubusercontent.com/49309686/232420532-f167b3fa-1e4c-41c5-aafe-c5c3d58f5ab8.png)

**Comment by keluokeda** [comment]
Mac跑Android也不行
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/16809185/233535542-02f8f022-8251-445d-b57a-2811649e4266.png">

**Comment by funnyzak** [comment]
https://github.com/facebook/react-native/issues/14952
https://github.com/facebook/react-native/issues/17423
以上，可以对照操作下。
